/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gamecrush;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DanDesktop
 */
public class PanelProductos extends javax.swing.JPanel {

    /**
     * Creates new form PanelProductos
     */
    
    ResultSet pro;
    Statement st;
    String nombre, tipo, proveedor;
    Double precio;
    int cantidad; 
    
    public PanelProductos() {
        initComponents();
        cargarProductos();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
   
    
    public void cargarProductos(){
        try {
            Connection conn = Conexion.GetConnection();
            try {
                st = conn.createStatement();
                pro = st.executeQuery("SELECT * FROM Productos");
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, e.getErrorCode()+": "+e.getMessage());
            }
            
            String [] columns ={"idProducto","Nombre","Tipo","precio","proveedor","cantidad"};
            DefaultTableModel tm = new DefaultTableModel(null,columns);
            
            while(pro.next()){
                String [] row = {pro.getString(1),pro.getString(2),pro.getString(3),"$ "+pro.getString(4),pro.getString(5),pro.getString(6)};
                tm.addRow(row);
            }
            jTable1.setModel(tm);
        } catch (SQLException e) {
            Logger.getLogger(GameCrush.class.getName()).log(Level.SEVERE,null,e);
        }
    }
    
    public void clearTextFields(){
        this.jTxtFldNombre.setText("");
        this.jTxtFldPrecio.setText("");
        this.jTxtFldProveedor.setText("");
        this.jComboBox1.setSelectedIndex(0);
        this.jTxtFldCantidad.setText("");
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTxtFldNombre = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jTxtFldProveedor = new javax.swing.JTextField();
        jTxtFldPrecio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jBtnInsert = new javax.swing.JButton();
        jBtnDelete = new javax.swing.JButton();
        jBtnUpdate = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTxtFldCantidad = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Seleccione>", "Consola", "Accesorio", "Juego" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre Producto");

        jLabel2.setText("Tipo");

        jLabel3.setText("Proveedor");

        jLabel4.setText("Precio");

        jBtnInsert.setText("Insert");
        jBtnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnInsertActionPerformed(evt);
            }
        });

        jBtnDelete.setText("Delete");
        jBtnDelete.setEnabled(false);
        jBtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDeleteActionPerformed(evt);
            }
        });

        jBtnUpdate.setText("Update");
        jBtnUpdate.setEnabled(false);
        jBtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnUpdateActionPerformed(evt);
            }
        });

        jLabel5.setText("Cantidad");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtFldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTxtFldPrecio)
                                    .addComponent(jTxtFldProveedor)
                                    .addComponent(jComboBox1, 0, 149, Short.MAX_VALUE)
                                    .addComponent(jTxtFldCantidad))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBtnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(97, 97, 97))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtFldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtFldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtFldProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jBtnInsert)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnUpdate)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtFldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnInsertActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "INSERT INTO gamecrush.productos(nombre_producto, tipo, precio, proveedor,cantidad) "
                + "VALUES(?,?,?,?,?)";
            Connection conn = Conexion.GetConnection();
            conn.setAutoCommit(false);
            PreparedStatement ps = conn.prepareStatement(sql);
            
            nombre = jTxtFldNombre.getText();
            tipo = (String)jComboBox1.getSelectedItem();
            precio = Double.parseDouble(jTxtFldPrecio.getText());
            proveedor = jTxtFldProveedor.getText();
            cantidad = Integer.parseInt(jTxtFldCantidad.getText());
            
            ps.setString(1, nombre);
            ps.setString(2, tipo);
            ps.setDouble(3, precio);
            ps.setString(4, proveedor);
            ps.setString(5, Integer.toString(cantidad));
            
            ps.execute();
            conn.commit();
            cargarProductos();
            clearTextFields();
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getErrorCode()+": "+e.getMessage());
        }
    }//GEN-LAST:event_jBtnInsertActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jBtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDeleteActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "DELETE FROM gamecrush.productos WHERE idProducto = '"+(String)jTable1.getValueAt(jTable1.getSelectedRow(), 0)+"';";
            Connection conn = Conexion.GetConnection();
            st = conn.createStatement();
            st.execute(sql);
            cargarProductos();
            clearTextFields();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getErrorCode()+": "+e.getMessage());
        }
        jBtnDelete.setEnabled(false);
        jBtnUpdate.setEnabled(false);
    }//GEN-LAST:event_jBtnDeleteActionPerformed

    private void jBtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnUpdateActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "Update gamecrush.productos "
                    + "SET nombre_producto = ?, "
                    + "tipo = ?, "
                    + "precio = ?, "
                    + "proveedor = ?, "
                    + "cantidad = ? "
                    + "WHERE idproductos = ?";
            Connection conn = Conexion.GetConnection();
            conn.setAutoCommit(false);
            PreparedStatement ps = conn.prepareStatement(sql);
            String idProducto = (String)jTable1.getValueAt(jTable1.getSelectedRow(), 0);
            this.nombre = jTxtFldNombre.getText();
            this.tipo = (String)jComboBox1.getSelectedItem();
            this.precio = Double.parseDouble(jTxtFldPrecio.getText());
            this.proveedor = jTxtFldProveedor.getText();
            this.cantidad = Integer.parseInt(jTxtFldCantidad.getText());
            
            
            ps.setString(1, nombre);
            ps.setString(2, tipo);
            ps.setDouble(3, precio);
            ps.setString(4, proveedor);
            ps.setInt(5, cantidad);
            ps.setString(6, idProducto);
            ps.executeUpdate();
            
            conn.commit();
            cargarProductos();
            clearTextFields();
            this.jBtnUpdate.setEnabled(false);
            this.jBtnDelete.setEnabled(false);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getErrorCode()+": "+e.getMessage());
        }
    }//GEN-LAST:event_jBtnUpdateActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        jBtnDelete.setEnabled(true);
        jBtnUpdate.setEnabled(true);
        
        this.jTxtFldNombre.setText((String)this.jTable1.getValueAt(jTable1.getSelectedRow(), 1));
        this.jTxtFldPrecio.setText(((String)this.jTable1.getValueAt(jTable1.getSelectedRow(), 3)).substring(2));
        this.jTxtFldProveedor.setText((String)this.jTable1.getValueAt(jTable1.getSelectedRow(),4));
        this.jTxtFldCantidad.setText((String)this.jTable1.getValueAt(jTable1.getSelectedRow(),5));
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnDelete;
    private javax.swing.JButton jBtnInsert;
    private javax.swing.JButton jBtnUpdate;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTxtFldCantidad;
    private javax.swing.JTextField jTxtFldNombre;
    private javax.swing.JTextField jTxtFldPrecio;
    private javax.swing.JTextField jTxtFldProveedor;
    // End of variables declaration//GEN-END:variables
}
