/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gamecrush;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DanDesktop
 */
public class PanelDirecciones extends javax.swing.JPanel {

    /**
     * Creates new form PanelDirecciones
     */
    public PanelDirecciones() {
        initComponents();
        cargarClientes();
        String [] columns ={"id Dirección","Calle","Colonia","Num Interior","Num Exterior","Estado","Pais","Ciudad","Codigo Postal","id Cliente"};
        
        DefaultTableModel tm = new DefaultTableModel(null,columns){
                @Override
                public boolean isCellEditable(int rowIndex, int colIndex){
                    return false;
                }
            };
        jTblDirecciones.setModel(tm);
        jLblCamposObligatorios.setVisible(false);
        disableCampos();
        
        Validacion v = new Validacion();
        v.Email(jTxtFldFind);
        v.SoloLetras(jTxtFldCalle);
        v.SoloLetras(jTxtFldCiudad);
        v.SoloLetras(jTxtFldColonia);
        v.SoloLetras(jTxtFldEstado);
        v.SoloLetras(jTxtFldPais);
        v.codigoPostal(jTxtFldCP);
        v.SoloNumeros(jTxtFldNumExt);
        v.SoloNumeros(jTxtFldNumInt);
    }
    int cont = 0;
    ResultSet cli;
    Statement st;
    String nombre,apellido_p, apellido_m, email, telefono;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
     public void disableCampos(){
        this.jTxtFldCP.setEnabled(false);
        this.jTxtFldCalle.setEnabled(false);
        this.jTxtFldCiudad.setEnabled(false);
        this.jTxtFldColonia.setEnabled(false);
        this.jTxtFldEstado.setEnabled(false);
        this.jTxtFldNumExt.setEnabled(false);
        this.jTxtFldNumInt.setEnabled(false);
        this.jTxtFldPais.setEnabled(false);
    }
     
     public void enableCampos(){
        this.jTxtFldCP.setEnabled(true);
        this.jTxtFldCalle.setEnabled(true);
        this.jTxtFldCiudad.setEnabled(true);
        this.jTxtFldColonia.setEnabled(true);
        this.jTxtFldEstado.setEnabled(true);
        this.jTxtFldNumExt.setEnabled(true);
        this.jTxtFldNumInt.setEnabled(true);
        this.jTxtFldPais.setEnabled(true);
    }
     
    
     public void clearTextFields(){
        this.jTxtFldCP.setText("");
        this.jTxtFldCalle.setText("");
        this.jTxtFldCiudad.setText("");
        this.jTxtFldColonia.setText("");
        this.jTxtFldEstado.setText("");
        this.jTxtFldNumExt.setText("");
        this.jTxtFldNumInt.setText("");
        this.jTxtFldPais.setText("");
     }
    
    public void cargarClientes(){
        try{
            Connection conn = Conexion.GetConnection();
            try {
                st = conn.createStatement();
                cli = st.executeQuery("SELECT * FROM Clientes");
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this,e.getErrorCode() + ":" + e.getMessage());
            }
            
            String [] columns ={"idCliente","Nombre","Apellido Paterno","Apellido Materno","Telefono","E-Mail"};
            
            DefaultTableModel tm = new DefaultTableModel(null,columns){
                @Override
                public boolean isCellEditable(int rowIndex, int colIndex){
                    return false;
                }
            };
            
            while(cli.next()){
                String [] row = {cli.getString(1),cli.getString(2),cli.getString(3),cli.getString(4),cli.getString(5),cli.getString(6)};
                tm.addRow(row);
            }
            jTblClientes.setModel(tm);
        }catch(SQLException e){
            Logger.getLogger(GameCrush.class.getName()).log(Level.SEVERE,null,e);
        }
    }
    
    public void cargarDirecciones(){
        try {
            String sql = "SELECT * FROM direccion WHERE Clientes_idClientes = ?";
            
            Connection conn = Conexion.GetConnection();
            conn.setAutoCommit(false);
            PreparedStatement ps = conn.prepareStatement(sql);
            
            ps.setString(1, (String)jTblClientes.getValueAt(jTblClientes.getSelectedRow(), 0));
            
            this.cli = ps.executeQuery();
            
            String [] columns ={"id Dirección","Calle","Colonia","Num Interior","Num Exterior","Estado","Pais","Ciudad","Codigo Postal","id Cliente"};
            DefaultTableModel tm = new DefaultTableModel(null,columns){
                @Override
                public boolean isCellEditable(int rowIndex, int colIndex){
                    return false;
                }
            };
            
            while(cli.next()){
                String [] row = {cli.getString(1),cli.getString(2),cli.getString(3),cli.getString(4),cli.getString(5),cli.getString(6),cli.getString(7),cli.getString(8),cli.getString(9),cli.getString(10)};
                tm.addRow(row);
            }
            
            jTblDirecciones.setModel(tm);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getErrorCode()+": "+e.getMessage());
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrllPnClientes = new javax.swing.JScrollPane();
        jTblClientes = new javax.swing.JTable();
        jTxtFldFind = new javax.swing.JTextField();
        jScrllPnDir = new javax.swing.JScrollPane();
        jTblDirecciones = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jBtnInsert = new javax.swing.JButton();
        jBtnUpdate = new javax.swing.JButton();
        jBtnDelete = new javax.swing.JButton();
        jTxtFldNumExt = new javax.swing.JTextField();
        jTxtFldCiudad = new javax.swing.JTextField();
        jTxtFldEstado = new javax.swing.JTextField();
        jTxtFldPais = new javax.swing.JTextField();
        jTxtFldCP = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTxtFldCalle = new javax.swing.JTextField();
        jTxtFldColonia = new javax.swing.JTextField();
        jTxtFldNumInt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLblCamposObligatorios = new javax.swing.JLabel();

        jTblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTblClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTblClientesMouseClicked(evt);
            }
        });
        jScrllPnClientes.setViewportView(jTblClientes);

        jTxtFldFind.setText("Buscar cliente por email");
        jTxtFldFind.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTxtFldFindMouseClicked(evt);
            }
        });
        jTxtFldFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtFldFindActionPerformed(evt);
            }
        });
        jTxtFldFind.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtFldFindKeyTyped(evt);
            }
        });

        jTblDirecciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTblDirecciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTblDireccionesMouseClicked(evt);
            }
        });
        jScrllPnDir.setViewportView(jTblDirecciones);

        jLabel8.setText("* Codigo Postal");

        jBtnInsert.setText("Insert");
        jBtnInsert.setEnabled(false);
        jBtnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnInsertActionPerformed(evt);
            }
        });

        jBtnUpdate.setText("Update");
        jBtnUpdate.setEnabled(false);
        jBtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnUpdateActionPerformed(evt);
            }
        });

        jBtnDelete.setText("Delete");
        jBtnDelete.setEnabled(false);
        jBtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDeleteActionPerformed(evt);
            }
        });

        jTxtFldNumExt.setMinimumSize(new java.awt.Dimension(6, 50));

        jTxtFldCiudad.setMinimumSize(new java.awt.Dimension(6, 50));

        jTxtFldEstado.setMinimumSize(new java.awt.Dimension(6, 50));

        jTxtFldPais.setMinimumSize(new java.awt.Dimension(6, 50));

        jTxtFldCP.setMinimumSize(new java.awt.Dimension(6, 50));

        jLabel1.setText("* Calle");

        jLabel2.setText("* Colonia");

        jLabel3.setText("Numero Interior");

        jLabel4.setText("* Numero Exterior");

        jLabel5.setText("* Ciudad");

        jTxtFldCalle.setMinimumSize(new java.awt.Dimension(6, 50));

        jTxtFldColonia.setMinimumSize(new java.awt.Dimension(6, 50));

        jTxtFldNumInt.setMinimumSize(new java.awt.Dimension(6, 50));

        jLabel6.setText("* Estado");

        jLabel7.setText("* Pais");

        jLblCamposObligatorios.setText("Los campos marcados con asterisco (*) son obligatorios.");
        jLblCamposObligatorios.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTxtFldNumInt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTxtFldNumExt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTxtFldCiudad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTxtFldEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTxtFldPais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTxtFldCP, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtFldCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtFldColonia, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jBtnInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLblCamposObligatorios, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtFldCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxtFldColonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTxtFldNumInt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTxtFldNumExt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTxtFldCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTxtFldEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTxtFldPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTxtFldCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnInsert)
                    .addComponent(jBtnUpdate)
                    .addComponent(jBtnDelete))
                .addGap(18, 18, 18)
                .addComponent(jLblCamposObligatorios)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTxtFldFind, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrllPnDir, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
                    .addComponent(jScrllPnClientes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTxtFldFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrllPnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrllPnDir, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("empty-statement")
    private void jBtnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnInsertActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "INSERT INTO direccion (calle, colonia, num_interior, num_exterior, estado, pais, ciudad, codigo_postal, clientes_idClientes) "
                    + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
            
            Connection conn = Conexion.GetConnection();
            conn.setAutoCommit(false);
            PreparedStatement ps = conn.prepareStatement(sql);
            
            if(((((("".equals(jTxtFldNumExt.getText()) || "".equals(jTxtFldCalle.getText())) || "".equals(jTxtFldCiudad.getText())) || "".equals(jTxtFldColonia.getText())) || "".equals(jTxtFldEstado.getText())) || "".equals(jTxtFldPais.getText())) ||
                    "".equals(jTxtFldCP.getText())){
                JOptionPane.showMessageDialog(this, "Por favor llene los campos obligatorios");
                jLblCamposObligatorios.setVisible(true);
            }else{
                ps.setString(1, jTxtFldCalle.getText());
                ps.setString(2, jTxtFldColonia.getText());
                
                if(!"".equals(jTxtFldNumInt.getText())){
                    ps.setString(3, jTxtFldNumInt.getText());
                }else{
                    ps.setString(3, "N/A");
                }
                
                ps.setString(4, jTxtFldNumExt.getText());
                ps.setString(5, jTxtFldEstado.getText());
                ps.setString(6, jTxtFldPais.getText());
                ps.setString(7, jTxtFldCiudad.getText());
                ps.setString(8, jTxtFldCP.getText());
                ps.setString(9, (String)this.jTblClientes.getValueAt(this.jTblClientes.getSelectedRow(), 0));
                
                ps.execute();
                conn.commit();
                
                
                cargarDirecciones();
                clearTextFields();
                disableCampos();
            }
            

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getErrorCode()+": "+e.getMessage());
        }
    }//GEN-LAST:event_jBtnInsertActionPerformed

    
    private void jTblClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblClientesMouseClicked
        // TODO add your handling code here:
        try {
            jBtnInsert.setEnabled(true);
            enableCampos();
            cargarDirecciones();
            clearTextFields();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_jTblClientesMouseClicked

    
    private void jBtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDeleteActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "DELETE FROM direccion WHERE `idDireccion` = ? ";
            
            Connection conn = Conexion.GetConnection();
            conn.setAutoCommit(false);
            PreparedStatement ps = conn.prepareStatement(sql);
            
            ps.setString(1, (String)jTblDirecciones.getValueAt(jTblDirecciones.getSelectedRow(), 0));
            
            ps.execute();
            conn.commit();
            
            cargarDirecciones();
            clearTextFields();
            
            
            jBtnDelete.setEnabled(false);
            jBtnUpdate.setEnabled(false);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getErrorCode()+": "+e.getMessage());
        }
    }//GEN-LAST:event_jBtnDeleteActionPerformed

    
    private void jBtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnUpdateActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "UPDATE direccion "
                    + "SET calle = ?, "
                    + "colonia = ?, "
                    + "num_interior = ?, "
                    + "num_exterior = ?, "
                    + "estado = ?, "
                    + "pais = ?, "
                    + "ciudad = ?, "
                    + "codigo_postal = ? "
                    + "WHERE idDireccion = ? ";
            
            Connection conn = Conexion.GetConnection();
            conn.setAutoCommit(false);
            PreparedStatement ps = conn.prepareStatement(sql);
            
            ps.setString(1, this.jTxtFldCalle.getText());
            ps.setString(2, this.jTxtFldColonia.getText());
            ps.setString(3, this.jTxtFldNumInt.getText());
            ps.setString(4, this.jTxtFldNumExt.getText());
            ps.setString(5, this.jTxtFldEstado.getText());
            ps.setString(6, this.jTxtFldPais.getText());
            ps.setString(7, this.jTxtFldCiudad.getText());
            ps.setString(8, this.jTxtFldCP.getText());
            ps.setString(9, (String)this.jTblDirecciones.getValueAt(this.jTblDirecciones.getSelectedRow(), 0));
            
            ps.executeUpdate();
            conn.commit();
            
            cargarDirecciones();
            clearTextFields();
            disableCampos();
            
            jBtnDelete.setEnabled(false);
            jBtnUpdate.setEnabled(false);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getErrorCode()+": "+e.getMessage());
        }
    }//GEN-LAST:event_jBtnUpdateActionPerformed

    
    private void jTblDireccionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblDireccionesMouseClicked
        // TODO add your handling code here:
            enableCampos();
            jBtnDelete.setEnabled(true);
            jBtnUpdate.setEnabled(true);
            
            jTxtFldCalle.setText((String)jTblDirecciones.getValueAt(jTblDirecciones.getSelectedRow(), 1));
            jTxtFldColonia.setText((String)jTblDirecciones.getValueAt(jTblDirecciones.getSelectedRow(), 2));
            jTxtFldNumInt.setText((String)jTblDirecciones.getValueAt(jTblDirecciones.getSelectedRow(), 3));
            jTxtFldNumExt.setText((String)jTblDirecciones.getValueAt(jTblDirecciones.getSelectedRow(), 4));
            jTxtFldEstado.setText((String)jTblDirecciones.getValueAt(jTblDirecciones.getSelectedRow(), 5));
            jTxtFldPais.setText((String)jTblDirecciones.getValueAt(jTblDirecciones.getSelectedRow(), 6));
            jTxtFldCiudad.setText((String)jTblDirecciones.getValueAt(jTblDirecciones.getSelectedRow(), 7));
            jTxtFldCP.setText((String)jTblDirecciones.getValueAt(jTblDirecciones.getSelectedRow(), 8));
            
    }//GEN-LAST:event_jTblDireccionesMouseClicked

    private void jTxtFldFindKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtFldFindKeyTyped
        // TODO add your handling code here:
        try {
            String sql = "SELECT * FROM clientes WHERE email LIKE ? ";
            Connection conn = Conexion.GetConnection();
            conn.setAutoCommit(false);
            PreparedStatement ps = conn.prepareCall(sql);
            
            ps.setString(1,"%"+this.jTxtFldFind.getText()+"%");
            
            cli = ps.executeQuery();
            
            String [] columns ={"idCliente","Nombre","Apellido Paterno","Apellido Materno","Telefono","E-Mail"};
            
            DefaultTableModel tm = new DefaultTableModel(null,columns){
                @Override
                public boolean isCellEditable(int rowIndex, int colIndex){
                    return false;
                }
            };
            
            while(cli.next()){
                String [] row = {cli.getString(1),cli.getString(2),cli.getString(3),cli.getString(4),cli.getString(5),cli.getString(6)};
                tm.addRow(row);
            }
            jTblClientes.setModel(tm);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getErrorCode() + ": " + e.getMessage());
        }
    }//GEN-LAST:event_jTxtFldFindKeyTyped

    private void jTxtFldFindMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTxtFldFindMouseClicked
        // TODO add your handling code here:
        this.jTxtFldFind.setText("");
    }//GEN-LAST:event_jTxtFldFindMouseClicked

    private void jTxtFldFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtFldFindActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtFldFindActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnDelete;
    private javax.swing.JButton jBtnInsert;
    private javax.swing.JButton jBtnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLblCamposObligatorios;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrllPnClientes;
    private javax.swing.JScrollPane jScrllPnDir;
    private javax.swing.JTable jTblClientes;
    private javax.swing.JTable jTblDirecciones;
    private javax.swing.JTextField jTxtFldCP;
    private javax.swing.JTextField jTxtFldCalle;
    private javax.swing.JTextField jTxtFldCiudad;
    private javax.swing.JTextField jTxtFldColonia;
    private javax.swing.JTextField jTxtFldEstado;
    private javax.swing.JTextField jTxtFldFind;
    private javax.swing.JTextField jTxtFldNumExt;
    private javax.swing.JTextField jTxtFldNumInt;
    private javax.swing.JTextField jTxtFldPais;
    // End of variables declaration//GEN-END:variables
}
